version: '3.8'

services:
  miahoot-front:
    image: miahoot/miahoot-front2
    ports:
      - "8080:80"
    depends_on:
      - miahoot-back

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s 

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6432:5432"

  miahoot-back:
    image: miahoot/miahoot-back2
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_ADDRESS: postgres
      #CONNEXION_STRING: postgres
      CONNEXION_STRING: jdbc:postgresql://postgres:5432/

    links:
      - postgres
